# Archivo: supabase/config.toml

# ====================================================
# 1. Función: send-contact-email
# ====================================================
[functions.send-contact-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-contact-email/deno.json"
entrypoint = "./functions/send-contact-email/index.ts"

# ====================================================
# 2. Función: generar-pedido-pdf
# ====================================================
[functions.generar-pedido-pdf]
enabled = true
verify_jwt = false
entrypoint = "./functions/generar-pedido-pdf/index.ts"

[functions.generar-pdf]
enabled = true
verify_jwt = true
import_map = "./functions/generar-pdf/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generar-pdf/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generar-pdf/*.html" ]
